'use strict';


const jsi10n = {
    mes : {
        'Manufacturer': 'Производитель',
        'Name': 'Название',
        'Comment': 'Комментарий',
        'User': 'Пользователь',
        'Login': 'Логин',
        'Place': 'Помещение',
        'Bar code': 'Штрихкод',
        'Date of change': 'Дата изменения',
        'Inventory number': 'Инв. номер',
        'Serial number': 'Серийный номер',
        'The page counter': 'Кол-во распечатанных страниц',
        'Counter': 'Счётчик',
        'Actions': 'Действие',
        'Are you sure you want to write off the selected printer?': 'Вы точно хотите списать выбранный принтер?',
        'Color': 'Цвет',
        'Firm': 'Контрагент',
        'Organization': 'Организация',
        'Are you sure you want to recycle printer?': 'Вы точно хотите утилизировать принтер?',
        'Actual': 'Актуален',
        'Number': 'Номер',
        'Type': 'Тип',
        'Title': 'Заголовок',
        'Date': 'Дата',
        'Amount, dollars': 'Сумма, руб.',
        'Spent, dollars': 'Потрачено, руб.',
        'Content': 'Содержимое',
        'Summary': 'Краткое содержание',
        'Full name': 'Фамилия, имя, отчество',
        'Complaint': 'Жалоба',
        'Are you sure you want to delete a document?': 'Вы точно хотите удалить документ?',
        'Not selected cartridges installed in the printer': 'Не выбраны картриджи для установки в принтер.',
        'Not selected a printer.': 'Не выбран принтер',
        'Are you sure you want to delete the user?': 'Вы точно хотите удалить пользователя?',
        'Are you sure you want to delete users?': 'Вы уверены, что хотите удалить пользователей?',
        'Amount<br/>recovery': 'Количество перезаправок',
        'Are you sure you want to move the cartridges to the basket?': 'Вы точно хотите передать картриджи на списание?',
        'Refill': 'Перезаправки',
        'Printer': 'Принтер',
        'Are you sure you want to delete consumable (s)?': 'Вы точно хотите удалить картридж(и)?',
        'You sure you want to return the selected items back to the store?': 'Вы точно хотите вернуть выбранные картриджи обратно на склад?',
        'Are you sure you want to remove the name?': 'Вы точно хотите удалить название?',
        'CCount': 'Счётчик',
        'Does not specify a value.': 'Не определено значение.',
        'Internal number': 'Внутренний номер',
        'Object type': 'Тип объекта',
        'Contract': 'Контракты',
        'Date of transfer': 'Дата передачи',
        'Who returned': 'Кто вернул',
        'Who served': 'Кто обслуживал',
        'Who gave': 'Кто передал',
        'Spent dollars': 'Потрачено, руб.',
        'Return date': 'Дата возврата',
        'Cartridge name': 'Название картриджа',
        'List of compatible cartridges': 'Перечень совместимых картриджей',
        'Are you sure you want to delete?': 'Вы точно хотите удалить?',
        'Contacts': 'Контакты',
        'Address': 'Адрес',
        'Are you sure you want to remove the counterparty?': 'Вы точно хотите удалить контрагента?',
        'Are you sure you want to return to stock?': 'Вы уверены, что хотите вернуть на склад?',
        'Branch': 'Филиал',
        'Branches': 'Филиалы',
        'Yes': 'Да',
        'Cancel': 'Отменить',
        'Close': 'Закрыть',
        'Ok': 'Хорошо',
        'Delete': 'Удалить',
        'Confirm': 'Подтверждение',
        'Are you sure you want to delete the printer with ID=34?': 'Вы точно хотите удалить принтер с ID=34?',
        'Please select at least one document.': 'Выберите хотя бы один документ.',
        'Warning': 'Предупреждение',
        'Are you sure you want to remove the selected item from the database?': 'Вы точно хотите удалить из БД выбранное?',
        'Removing the operating system': 'Удаление операционной системы',
        'The operating system will be removed permanently. Are you sure?': 'Операционная система будет удалена навсегда. Вы уверены?',
        'Component information': 'Информация о компоненте',
        'Quantity, pieces': 'Кол-во, штук',
    },
    _ : function(key) {
        return this.mes[key]
    }

}
